/**
 * Core data models for Character Star Stats
 */

/**
 * Represents a distinct category or dimension of player accomplishment
 */
export interface Area {
  _id: string;        // Unique identifier (kebab-case)
  title: string;      // Display name
}

/**
 * Represents a progression milestone within a specific area
 */
export interface Level {
  _id?: string;       // Auto-generated by API
  area: string;       // Parent area ID
  level: string;      // Display name
  position: number;   // Order within area (0-based)
  minPoints: number;  // Points required to reach this level
}

/**
 * Represents player progress statistics across all areas
 */
export interface PlayerStats {
  player: string;
  stats: AreaStat[];
}

/**
 * Represents player statistics for a specific area
 */
export interface AreaStat {
  area: string;
  percent_completed: number;
  next_points: number;
  next_level: Level;
  total_levels: number;
}
